pacing_functions:
  linear:
    start: 0.1
    end: 1.0
    steps: 10000
  exponential:
    start: 0.1
    end: 1.0
    gamma: 0.999
  step:
    milestones: [2000, 5000, 8000]
    values: [0.2, 0.5, 0.8, 1.0]